name: QCN Barras
favicon: null
layout_spectrum: 0.9587660788092762
typography_spectrum: 0.4195406816434115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5772854709066451
  lightness: 0.3026825019624084
  saturation: 0.3591390650253743
  rhythmicContrast: 0.21267687366344035
purpose: []
