name: QCN Barras
favicon: null
layout_spectrum: 0.12575
typography_spectrum: 0.02106
title: 'Quinta Casal Novo Wines '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1e2829'
    - '#6e7049'
    - '#a8bf30'
    - '#9b2635'
  brandStrength: 0.5625
  lightness: 0.3026825019624084
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
