name: QCN Barras
favicon: null
layout_spectrum: 0.12575
typography_spectrum: 0.02106
title: 'Quinta Casal Novo Wines '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31450a'
    - '#78b1fe'
    - '#d1e217'
    - '#6e8444'
    - '#fcffc0'
  brandStrength: 0.5625
  lightness: 0.3026825019624084
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
